export const EMPLOYEE_REPOSITORY = "EMPLOYEE_REPOSITORY";
export const EMPLOYEE_SERVICE = "EMPLOYEE_SERVICE";
export const EMPLOYEE_CONTROLLER = "EMPLOYEE_CONTROLLER";
export const EMPLOYEE_PROVIDER = "EMPLOYEE_PROVIDER";