//basic provider
export const ACCOUNT_ROLE_PROVIDER = 'ACCOUNT_ROLE_PROVIDER';
export const ACCOUNT_PROVIDER = 'ACCOUNT_PROVIDER';
export const ROLE_PROVIDER = 'ROLE_PROVIDER';

//bpmn provider
export const WORK_FLOW_CONNECTION_PROVIDER = 'WORK_FLOW_CONNECTION_PROVIDER';
export const WORK_FLOW_PROVIDER = 'WORK_FLOW_PROVIDER';
export const WORK_FLOW_INSTANCE_PROVIDER = 'WORK_FLOW_INSTANCE_PROVIDER';
