//basic repository
export const ACCOUNT_ROLE_REPOSITORY = 'ACCOUNT_ROLE_REPOSITORY';
export const ACCOUNT_REPOSITORY = 'ACCOUNT_REPOSITORY';
export const ROLE_REPOSITORY = 'ROLE_REPOSITORY';

//bpmn repository
export const WORK_FLOW_CONNECTION_REPOSITORY = 'WORK_FLOW_CONNECTION_REPOSITORY';
export const WORK_FLOW_REPOSITORY = 'WORK_FLOW_REPOSITORY';
export const WORK_FLOW_INSTANCE_REPOSITORY = 'WORK_FLOW_INSTANCE_REPOSITORY';
