export const FORM_VALUE_REPOSITORY = "FORM_VALUE_REPOSITORY";
export const FORM_VALUE_SERVICE = "FORM_VALUE_SERVICE";
export const FORM_VALUE_CONTROLLER = "FORM_VALUE_CONTROLLER";
export const FORM_VALUE_PROVIDER = "FORM_VALUE_PROVIDER";