export const FORM_DATA_REPOSITORY = "FORM_DATA_REPOSITORY";
export const FORM_DATA_SERVICE = "FORM_DATA_SERVICE";
export const FORM_DATA_CONTROLLER = "FORM_DATA_CONTROLLER";
export const FORM_DATA_PROVIDER = "FORM_DATA_PROVIDER";