export const FORM_GROUP_REPOSITORY = "FORM_GROUP_REPOSITORY";
export const FORM_GROUP_SERVICE = "FORM_GROUP_SERVICE";
export const FORM_GROUP_CONTROLLER = "FORM_GROUP_CONTROLLER";
export const FORM_GROUP_PROVIDER = "FORM_GROUP_PROVIDER";