export const FORM_CONTROL_REPOSITORY = "FORM_CONTROL_REPOSITORY";
export const FORM_CONTROL_SERVICE = "FORM_CONTROL_SERVICE";
export const FORM_CONTROL_CONTROLLER = "FORM_CONTROL_CONTROLLER";
export const FORM_CONTROL_PROVIDER = "FORM_CONTROL_PROVIDER";