export const PRODUCT_EXTRA_VALUE_REPOSITORY = "PRODUCT_EXTRA_VALUE_REPOSITORY";
export const PRODUCT_EXTRA_VALUE_SERVICE = "PRODUCT_EXTRA_VALUE_SERVICE";
export const PRODUCT_EXTRA_VALUE_CONTROLLER = "PRODUCT_EXTRA_VALUE_CONTROLLER";
export const PRODUCT_EXTRA_VALUE_PROVIDER = "PRODUCT_EXTRA_VALUE_PROVIDER";