export const PRODUCT_REPOSITORY = "PRODUCT_REPOSITORY";
export const PRODUCT_SERVICE = "PRODUCT_SERVICE";
export const PRODUCT_CONTROLLER = "PRODUCT_CONTROLLER";
export const PRODUCT_PROVIDER = "PRODUCT_PROVIDER";