export const ACTIVITY_REPOSITORY = "ACTIVITY_REPOSITORY";
export const ACTIVITY_SERVICE = "ACTIVITY_SERVICE";
export const ACTIVITY_CONTROLLER = "ACTIVITY_CONTROLLER";
export const ACTIVITY_PROVIDER = "ACTIVITY_PROVIDER";