export const ATTACHMENT_REPOSITORY = "ATTACHMENT_REPOSITORY";
export const ATTACHMENT_SERVICE = "ATTACHMENT_SERVICE";
export const ATTACHMENT_CONTROLLER = "ATTACHMENT_CONTROLLER";
export const ATTACHMENT_PROVIDER = "ATTACHMENT_PROVIDER";