export const CAMPAIGN_GROUP_REPOSITORY = "CAMPAIGN_GROUP_REPOSITORY";
export const CAMPAIGN_GROUP_SERVICE = "CAMPAIGN_GROUP_SERVICE";
export const CAMPAIGN_GROUP_CONTROLLER = "CAMPAIGN_GROUP_CONTROLLER";
export const CAMPAIGN_GROUP_PROVIDER = "CAMPAIGN_GROUP_PROVIDER";