export const CAMPAIGN_REPOSITORY = "CAMPAIGN_REPOSITORY";
export const CAMPAIGN_SERVICE = "CAMPAIGN_SERVICE";
export const CAMPAIGN_CONTROLLER = "CAMPAIGN_CONTROLLER";
export const CAMPAIGN_PROVIDER = "CAMPAIGN_PROVIDER";