export const DEAL_DETAIL_REPOSITORY = "DEAL_DETAIL_REPOSITORY";
export const DEAL_DETAIL_SERVICE = "DEAL_DETAIL_SERVICE";
export const DEAL_DETAIL_CONTROLLER = "DEAL_DETAIL_CONTROLLER";
export const DEAL_DETAIL_PROVIDER = "DEAL_DETAIL_PROVIDER";