export const PIPELINE_REPOSITORY = "PIPELINE_REPOSITORY";
export const PIPELINE_SERVICE = "PIPELINE_SERVICE";
export const PIPELINE_CONTROLLER = "PIPELINE_CONTROLLER";
export const PIPELINE_PROVIDER = "PIPELINE_PROVIDER";