export const PROCESS_CONNECTION_REPOSITORY = "PROCESS_CONNECTION_REPOSITORY";
export const PROCESS_CONNECTION_SERVICE = "PROCESS_CONNECTION_SERVICE";
export const PROCESS_CONNECTION_CONTROLLER = "PROCESS_CONNECTION_CONTROLLER";
export const PROCESS_CONNECTION_PROVIDER = "PROCESS_CONNECTION_PROVIDER";