export const PROCESS_REPOSITORY = "PROCESS_REPOSITORY";
export const PROCESS_SERVICE = "PROCESS_SERVICE";
export const PROCESS_CONTROLLER = "PROCESS_CONTROLLER";
export const PROCESS_PROVIDER = "PROCESS_PROVIDER";