export const PROCESS_STEP_INSTANCE_REPOSITORY = "PROCESS_STEP_INSTANCE_REPOSITORY";
export const PROCESS_STEP_INSTANCE_SERVICE = "PROCESS_STEP_INSTANCE_SERVICE";
export const PROCESS_STEP_INSTANCE_CONTROLLER = "PROCESS_STEP_INSTANCE_CONTROLLER";
export const PROCESS_STEP_INSTANCE_PROVIDER = "PROCESS_STEP_INSTANCE_PROVIDER";