export const PROCESS_STEP_REPOSITORY = "PROCESS_STEP_REPOSITORY";
export const PROCESS_STEP_SERVICE = "PROCESS_STEP_SERVICE";
export const PROCESS_STEP_CONTROLLER = "PROCESS_STEP_CONTROLLER";
export const PROCESS_STEP_PROVIDER = "PROCESS_STEP_PROVIDER";