export const PROCESS_INSTANCE_REPOSITORY = "PROCESS_INSTANCE_REPOSITORY";
export const PROCESS_INSTANCE_SERVICE = "PROCESS_INSTANCE_SERVICE";
export const PROCESS_INSTANCE_CONTROLLER = "PROCESS_INSTANCE_CONTROLLER";
export const PROCESS_INSTANCE_PROVIDER = "PROCESS_INSTANCE_PROVIDER";