export const WF_INSTANCE_REPOSITORY = "WF_INSTANCE_REPOSITORY";
export const WF_INSTANCE_SERVICE = "WF_INSTANCE_SERVICE";
export const WF_INSTANCE_CONTROLLER = "WF_INSTANCE_CONTROLLER";
export const WF_INSTANCE_PROVIDER = "WF_INSTANCE_PROVIDER";