export const WORK_FLOW_CONNECTION_REPOSITORY = "WORK_FLOW_CONNECTION_REPOSITORY";
export const WORK_FLOW_CONNECTION_SERVICE = "WORK_FLOW_CONNECTION_SERVICE";
export const WORK_FLOW_CONNECTION_CONTROLLER = "WORK_FLOW_CONNECTION_CONTROLLER";
export const WORK_FLOW_CONNECTION_PROVIDER = "WORK_FLOW_CONNECTION_PROVIDER";