export const WF_CONNECTION_REPOSITORY = "WF_CONNECTION_REPOSITORY";
export const WF_CONNECTION_SERVICE = "WF_CONNECTION_SERVICE";
export const WF_CONNECTION_CONTROLLER = "WF_CONNECTION_CONTROLLER";
export const WF_CONNECTION_PROVIDER = "WF_CONNECTION_PROVIDER";