export const WF_STEP_REPOSITORY = "WF_STEP_REPOSITORY";
export const WF_STEP_SERVICE = "WF_STEP_SERVICE";
export const WF_STEP_CONTROLLER = "WF_STEP_CONTROLLER";
export const WF_STEP_PROVIDER = "WF_STEP_PROVIDER";