export const WORK_FLOW_REPOSITORY = "WORK_FLOW_REPOSITORY";
export const WORK_FLOW_SERVICE = "WORK_FLOW_SERVICE";
export const WORK_FLOW_CONTROLLER = "WORK_FLOW_CONTROLLER";
export const WORK_FLOW_PROVIDER = "WORK_FLOW_PROVIDER";