export const WORK_FLOW_INSTANCE_REPOSITORY = "WORK_FLOW_INSTANCE_REPOSITORY";
export const WORK_FLOW_INSTANCE_SERVICE = "WORK_FLOW_INSTANCE_SERVICE";
export const WORK_FLOW_INSTANCE_CONTROLLER = "WORK_FLOW_INSTANCE_CONTROLLER";
export const WORK_FLOW_INSTANCE_PROVIDER = "WORK_FLOW_INSTANCE_PROVIDER";