export const WF_STEP_INSTANCE_REPOSITORY = "WF_STEP_INSTANCE_REPOSITORY";
export const WF_STEP_INSTANCE_SERVICE = "WF_STEP_INSTANCE_SERVICE";
export const WF_STEP_INSTANCE_CONTROLLER = "WF_STEP_INSTANCE_CONTROLLER";
export const WF_STEP_INSTANCE_PROVIDER = "WF_STEP_INSTANCE_PROVIDER";