export const CATEGORY_REPOSITORY = "CATEGORY_REPOSITORY";
export const CATEGORY_SERVICE = "CATEGORY_SERVICE";
export const CATEGORY_CONTROLLER = "CATEGORY_CONTROLLER";
export const CATEGORY_PROVIDER = "CATEGORY_PROVIDER";