export const TICKET_REPOSITORY = "TICKET_REPOSITORY";
export const TICKET_SERVICE = "TICKET_SERVICE";
export const TICKET_CONTROLLER = "TICKET_CONTROLLER";
export const TICKET_PROVIDER = "TICKET_PROVIDER";