export const ACCOUNT_DEPARTMENT_REPOSITORY = "ACCOUNT_DEPARTMENT_REPOSITORY";
export const ACCOUNT_DEPARTMENT_SERVICE = "ACCOUNT_DEPARTMENT_SERVICE";
export const ACCOUNT_DEPARTMENT_CONTROLLER = "ACCOUNT_DEPARTMENT_CONTROLLER";
export const ACCOUNT_DEPARTMENT_PROVIDER = "ACCOUNT_DEPARTMENT_PROVIDER";