export const ACCOUNT_REPOSITORY = "ACCOUNT_REPOSITORY";
export const ACCOUNT_SERVICE = "ACCOUNT_SERVICE";
export const ACCOUNT_CONTROLLER = "ACCOUNT_CONTROLLER";
export const ACCOUNT_PROVIDER = "ACCOUNT_PROVIDER";