export const ACCOUNT_EXTRA_VALUE_REPOSITORY = "ACCOUNT_EXTRA_VALUE_REPOSITORY";
export const ACCOUNT_EXTRA_VALUE_SERVICE = "ACCOUNT_EXTRA_VALUE_SERVICE";
export const ACCOUNT_EXTRA_VALUE_CONTROLLER = "ACCOUNT_EXTRA_VALUE_CONTROLLER";
export const ACCOUNT_EXTRA_VALUE_PROVIDER = "ACCOUNT_EXTRA_VALUE_PROVIDER";