export const ACCOUNT_ROLE_REPOSITORY = "ACCOUNT_ROLE_REPOSITORY";
export const ACCOUNT_ROLE_SERVICE = "ACCOUNT_ROLE_SERVICE";
export const ACCOUNT_ROLE_CONTROLLER = "ACCOUNT_ROLE_CONTROLLER";
export const ACCOUNT_ROLE_PROVIDER = "ACCOUNT_ROLE_PROVIDER";