export const COMMENT_REPOSITORY = "COMMENT_REPOSITORY";
export const COMMENT_SERVICE = "COMMENT_SERVICE";
export const COMMENT_CONTROLLER = "COMMENT_CONTROLLER";
export const COMMENT_PROVIDER = "COMMENT_PROVIDER";