export const CUSTOMER_REPOSITORY = "CUSTOMER_REPOSITORY";
export const CUSTOMER_SERVICE = "CUSTOMER_SERVICE";
export const CUSTOMER_CONTROLLER = "CUSTOMER_CONTROLLER";
export const CUSTOMER_PROVIDER = "CUSTOMER_PROVIDER";