export const DEPARTMENT_REPOSITORY = "DEPARTMENT_REPOSITORY";
export const DEPARTMENT_SERVICE = "DEPARTMENT_SERVICE";
export const DEPARTMENT_CONTROLLER = "DEPARTMENT_CONTROLLER";
export const DEPARTMENT_PROVIDER = "DEPARTMENT_PROVIDER";