export const DEVICE_REPOSITORY = "DEVICE_REPOSITORY";
export const DEVICE_SERVICE = "DEVICE_SERVICE";
export const DEVICE_CONTROLLER = "DEVICE_CONTROLLER";
export const DEVICE_PROVIDER = "DEVICE_PROVIDER";