export const EXTRA_INFORMATION_REPOSITORY = "EXTRA_INFORMATION_REPOSITORY";
export const EXTRA_INFORMATION_SERVICE = "EXTRA_INFORMATION_SERVICE";
export const EXTRA_INFORMATION_CONTROLLER = "EXTRA_INFORMATION_CONTROLLER";
export const EXTRA_INFORMATION_PROVIDER = "EXTRA_INFORMATION_PROVIDER";