export const NOTIFICATION_REPOSITORY = "NOTIFICATION_REPOSITORY";
export const NOTIFICATION_SERVICE = "NOTIFICATION_SERVICE";
export const NOTIFICATION_CONTROLLER = "NOTIFICATION_CONTROLLER";
export const NOTIFICATION_PROVIDER = "NOTIFICATION_PROVIDER";