export const PATTERN_REPOSITORY = "PATTERN_REPOSITORY";
export const PATTERN_SERVICE = "PATTERN_SERVICE";
export const PATTERN_CONTROLLER = "PATTERN_CONTROLLER";
export const PATTERN_PROVIDER = "PATTERN_PROVIDER";