export const TRIGGER_REPOSITORY = "TRIGGER_REPOSITORY";
export const TRIGGER_SERVICE = "TRIGGER_SERVICE";
export const TRIGGER_CONTROLLER = "TRIGGER_CONTROLLER";
export const TRIGGER_PROVIDER = "TRIGGER_PROVIDER";