export const FEEDBACK_REPOSITORY = "FEEDBACK_REPOSITORY";
export const FEEDBACK_SERVICE = "FEEDBACK_SERVICE";
export const FEEDBACK_CONTROLLER = "FEEDBACK_CONTROLLER";
export const FEEDBACK_PROVIDER = "FEEDBACK_PROVIDER";