export const ORDER_REQUEST_REPOSITORY = "ORDER_REQUEST_REPOSITORY";
export const ORDER_REQUEST_SERVICE = "ORDER_REQUEST_SERVICE";
export const ORDER_REQUEST_CONTROLLER = "ORDER_REQUEST_CONTROLLER";
export const ORDER_REQUEST_PROVIDER = "ORDER_REQUEST_PROVIDER";