export const SERVICE_REPOSITORY = "SERVICE_REPOSITORY";
export const SERVICE_SERVICE = "SERVICE_SERVICE";
export const SERVICE_CONTROLLER = "SERVICE_CONTROLLER";
export const SERVICE_PROVIDER = "SERVICE_PROVIDER";